### ISSUE TITLE
abort parameter in index.d.ts

### ISSUE THREAD

**Issue by srgykuz** [ticinum-aerospace/leaflet-wms-header#1]
What does `abort` parameters means? For that purposes it is used? I didn't find any place of this parameter usage in the code. It is also missed in documentation.
![1](https://user-images.githubusercontent.com/20613502/58161491-03586800-7c89-11e9-9ebd-99eae5bef40a.png)

**Comment by ticinum-aerospace** [comment]
> What does `abort` parameters means? For that purposes it is used? I didn't find any place of this parameter usage in the code. It is also missed in documentation.
> ![1](https://user-images.githubusercontent.com/20613502/58161491-03586800-7c89-11e9-9ebd-99eae5bef40a.png)

Sorry for the late reply. I updated the documentation. Hope you will enjoy it
