### ISSUE TITLE
Abort parameter: documentation OR TypeScript definitions wrong

### ISSUE THREAD

**Issue by Snaptags** [ticinum-aerospace/leaflet-wms-header#10]
The documentation claims that you can pass "null" as abort parameter, but the TypeScript definition file requires passing an Observable.

**Comment by ticinum-aerospace** [comment]
Thank you @Snaptags

**Comment by Snaptags** [comment]
Could you perhaps trigger a release to npm?

**Comment by SugarLin** [comment]
Thank you @ticinum-aerospace, but I would like to use it in Typescript and Angular also, would you trigger a release to npm? for the optional abort and results (version 1.0.13).
Thank you very much in advance.
