### ISSUE TITLE
Wrong header parse

### ISSUE THREAD

**Issue by hitokiri** [ticinum-aerospace/leaflet-wms-header#12]
I am using this extension, but when trying to send the header,
![image](https://user-images.githubusercontent.com/247528/84177350-fba86480-aa3f-11ea-98d4-d84ee20319e2.png)

 this appears on the server side.

**'access-control-request-headers': 'authorization',**

it should look like this :
![image](https://user-images.githubusercontent.com/247528/84178158-34950900-aa41-11ea-9ff4-ef61ec6af760.png)

Note:  this part was modified to work only with TILDE

![image](https://user-images.githubusercontent.com/247528/84177667-65c10980-aa40-11ea-8178-cce12f03ab65.png)

**Comment by khaledboka** [comment]
@hitokiri 
Hello, I know it seems really late to reply, but I just found out that this is a "CORS" error

In my case, I tried using Postman, and the request worked just fine

Then I tried to fix the CORS headers issue from Nginx (my current proxy server) it has been solved for good

**Comment by ticinum-aerospace** [comment]
It's a CORS issue, not related with leaflet
