### ISSUE TITLE
Cannot find name 'WMSHeader'

### ISSUE THREAD

**Issue by albertomusetti** [ticinum-aerospace/leaflet-wms-header#3]
Ciao,
when I import 'leaflet-wms-header', the IDE show this error:

 ERROR in node_modules/leaflet-wms-header/index.d.ts(20,8): error TS2304: Cannot find name 'WMSHeader'.

Dependencies:
@angular: 8,2
@leaflet: 1.5

**Comment by svrijsewijk** [comment]
Same issue
https://github.com/ticinum-aerospace/leaflet-wms-header/pull/5

**Comment by MarsXan** [comment]
Same issue

**Comment by gdbd** [comment]
@ellvtr @ticinum-aerospace please, publish this update to npm package

**Comment by ellvtr** [comment]
Strange. Also there is no line 20 in that file, so how could there be an error on line 20, column 8?
https://github.com/ticinum-aerospace/leaflet-wms-header/blob/master/index.d.ts
Which IDE do you use?

**Comment by ticinum-aerospace** [comment]
I published last release. Thanks for using our plugin. :D

**Comment by smahamed** [comment]
it has dependency on rxjs 6.6.7, and i am using 7.5.0. Can it be upgraded ?
