### ISSUE TITLE
Response headers from source URL not present in client

### ISSUE THREAD

**Issue by rajanski** [ticinum-aerospace/leaflet-wms-header#6]
Hi and first of all thanks for that tool, it works basically, but in order to work with CORS, I need the response headers in the returned object.. any hints how to do this?

**Comment by ticinum-aerospace** [comment]
> Hi and first of all thanks for that tool, it works basically, but in order to work with CORS, I need the response headers in the returned object.. any hints how to do this?

Hi, can you provide me some code to replicate your problem? Thanks

**Comment by ticinum-aerospace** [comment]
Closed due inactivity
